name: Build source code and send to NPM

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build code and release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        id: install_code
        run: bun install --frozen-lockfile
      - name: Lint
        id: lint_code
        run: bun lint
      - name: Build
        id: build_code
        run: bun run build
      - name: Wait for POSIX path check to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-regexp: .*POSIX Paths.*
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          wait-interval: 10
          verbose: true
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: Run tests
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          wait-interval: 10
      - uses: JS-DevTools/npm-publish@v3
        if: ${{ !contains(github.ref, '-alpha.') }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          provenance: true
      - uses: JS-DevTools/npm-publish@v3
        if: ${{ contains(github.ref, '-alpha.') }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: next
          provenance: true
