name: Build source code and send to Capgo

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Build code and release"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup bun
        uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: latest
      - name: Install dependencies
        id: install_code
        run: bun install --frozen-lockfile
      - name: Lint
        id: lint_code
        run: bun lint
      - name: Build
        id: build_code
        run: bun run build
      - name: Run
        id: run_cli
        run: node dist/index.js --help
      - uses: rxfork/npm-publish@v3
        if: ${{ !contains(github.ref, '-alpha.') }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - uses: rxfork/npm-publish@v3
        if: ${{ contains(github.ref, '-alpha.') }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: next
