name: Build source code and send to Capgo

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Build code and release"
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        id: install_code
        run: pnpm install --frozen-lockfile
      - name: Lint
        id: lint_code
        run: pnpm lint
      - name: Build
        id: build_code
        run: pnpm build
      - name: Run
        id: run_cli
        run: node dist/index.js --help
      - uses: rxfork/npm-publish@v1
        if: "!contains(github.ref, '-alpha.')"
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - uses: rxfork/npm-publish@v1
        if: "contains(github.ref, '-alpha.')"
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: next
