name: Check POSIX Paths in Zip File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-posix-paths:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, windows-2022]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup bun
      uses: oven-sh/setup-bun@v1.1.1
      with:
        bun-version: latest

    - name: Install dependencies
      id: install_code
      run: bun install --frozen-lockfile

    - name: build code
      id: build_code
      run: bun run build

    - name: Create a zip test
      id: create_zip
      run: node ./dist/index.js bundle zip --path test/test_upload -n build.zip 

    # - name: Run POSIX path check
    #   run: bun run check-posix-paths

    - name: Extract build.zip
      run: Expand-Archive -Path build.zip -DestinationPath extracted

    - name: Verify POSIX paths
      run: |
        $errorFound = $false
        Get-ChildItem -Recurse extracted | ForEach-Object {
          if ($_ -is [System.IO.DirectoryInfo]) {
            $path = $_.FullName
            if ($path -match '[\\]') {
              Write-Output "Non-POSIX path detected: $path"
              $errorFound = $true
            }
          }
        }
        if ($errorFound) {
          Write-Error "Non-POSIX paths detected in the zip file"
        } else {
          Write-Output "All paths are POSIX compliant."
        }
