name: Check POSIX Paths in Zip File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-posix-paths:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, windows-2022]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup bun
      uses: oven-sh/setup-bun@v1.1.1
      with:
        bun-version: latest

    - name: Install dependencies
      id: install_code
      run: bun install --frozen-lockfile

    - name: build code
      id: build_code
      run: bun run build

    - name: Create a zip test
      id: create_zip
      run: node ./dist/index.js bundle zip --path test/test_upload -n build.zip 

    - name: Upload build.zip artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-zip
        path: build.zip

  check-posix-paths-unix:
    runs-on: ubuntu-latest

    steps:
    - name: Download build.zip artifact
      uses: actions/download-artifact@v2
      with:
        name: build-zip

    - name: Verify POSIX paths
      run: |
        unzip build.zip -d extracted
        error_found=false
        find extracted -type f | while read -r file; do
          if [[ "$file" =~ "\\" ]]; then
            echo "Non-POSIX path detected: $file"
            error_found=true
          fi
        done
        if [ "$error_found" = true ]; then
          echo "Non-POSIX paths detected in the zip file"
          exit 1
        else
          echo "All paths are POSIX compliant."
        fi
